{
  "openapi": "3.1.0",
  "x-stoplight": {
    "id": "8hprt4sv5oba4"
  },
  "info": {
    "version": "1.0",
    "title": "check1-3.1"
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/users/{userId}": {
      "get": {
        "summary": "Get User Info by User ID",
        "description": "Retrieve the information of the user with the matching user ID.",
        "operationId": "get-users-userId",
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "description": "Id of an existing user.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "Get User Alice Smith": {
                    "value": {
                      "id": 142,
                      "firstName": "Alice",
                      "lastName": "Smith",
                      "email": "alice.smith@gmail.com",
                      "dateOfBirth": "1997-10-31",
                      "emailVerified": true,
                      "signUpDate": "2019-08-24"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User Not Found"
          }
        },
        "servers": [
          {
            "url": "http://localhost:3000"
          }
        ],
        "x-stoplight": {
          "id": "7zzs1vzb5ff14"
        }
      },
      "patch": {
        "summary": "Update User Information",
        "description": "Update the information of an existing user.",
        "operationId": "patch-users-userId",
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "description": "Id of an existing user.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "description": "Patch user properties to update.",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string",
                    "description": "If a new email is given, the user's email verified property will be set to false."
                  },
                  "dateOfBirth": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "Update First Name": {
                  "value": {
                    "firstName": "Rebecca"
                  }
                },
                "Update Email": {
                  "value": {
                    "email": "rebecca@gmail.com"
                  }
                },
                "Update Last Name & Date of Birth": {
                  "value": {
                    "lastName": "Baker",
                    "dateOfBirth": "1985-10-02"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User Updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "Updated User Rebecca Baker": {
                    "value": {
                      "id": 13,
                      "firstName": "Rebecca",
                      "lastName": "Baker",
                      "email": "rebecca@gmail.com",
                      "dateOfBirth": "1985-10-02",
                      "emailVerified": false,
                      "createDate": "2019-08-24"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User Not Found"
          },
          "409": {
            "description": "Email Already Taken"
          }
        },
        "servers": [
          {
            "url": "http://localhost:3000"
          }
        ],
        "x-stoplight": {
          "id": "2a0wef4clu2yj"
        }
      }
    },
    "/user": {
      "post": {
        "summary": "Create New User",
        "description": "Create a new user.",
        "operationId": "post-user",
        "requestBody": {
          "description": "Post the necessary fields for the API to create a new user.",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "dateOfBirth": {
                    "type": "string",
                    "format": "date"
                  }
                },
                "required": [
                  "firstName",
                  "lastName",
                  "email",
                  "dateOfBirth"
                ]
              },
              "examples": {
                "Create User Bob Fellow": {
                  "value": {
                    "firstName": "Bob",
                    "lastName": "Fellow",
                    "email": "bob.fellow@gmail.com",
                    "dateOfBirth": "1996-08-24"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "New User Bob Fellow": {
                    "value": {
                      "id": 12,
                      "firstName": "Bob",
                      "lastName": "Fellow",
                      "email": "bob.fellow@gmail.com",
                      "dateOfBirth": "1996-08-24",
                      "emailVerified": false,
                      "createDate": "2020-11-18"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Missing Required Information"
          },
          "409": {
            "description": "Email Already Taken"
          }
        },
        "servers": [
          {
            "url": "http://localhost:3000"
          }
        ],
        "x-stoplight": {
          "id": "bbdgkz1rzp7be"
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "$ref": "#/components/schemas/M2",
        "title": "User",
        "examples": [
          {
            "id": 142,
            "firstName": "Alice",
            "lastName": "Smith",
            "email": "alice.smith@gmail.com",
            "dateOfBirth": "1997-10-31",
            "emailVerified": true,
            "signUpDate": "2019-08-24"
          }
        ],
        "x-stoplight": {
          "id": "g0n1f184863xa"
        }
      },
      "M2": {
        "type": "object",
        "title": "M2",
        "properties": {
          "uid": {
            "type": "number"
          },
          "fid": {
            "$ref": "#/components/schemas/M1",
            "type": "integer"
          },
          "pid": {
            "type": "array"
          }
        },
        "x-stoplight": {
          "id": "gheiy9nu57t5o"
        }
      },
      "M1": {
        "type": "object",
        "title": "M1",
        "properties": {
          "id": {
            "type": "integer"
          },
          "tt": {
            "type": "string"
          },
          "yy": {
            "$ref": "#/components/schemas/M2",
            "type": "string"
          },
          "rere": {
            "type": "object"
          },
          "ccvcvc": {
            "type": "array"
          }
        },
        "x-stoplight": {
          "id": "v1j4qes1zpa25"
        }
      }
    }
  }
}